### ISSUE TITLE
TypeError: samplerate must be specified

### ISSUE THREAD

**Issue by mabangbangtadie** [eurecom-asp/RawGAT-ST-antispoofing#3]
hi,when I evaluated own model on LA evaluation dataset: I found one error,could not solve it, I found in Modle.py already writed ,the samplerare=16000, why indidate this error. follow is two pictures of this question. thanks.
![捕获1](https://user-images.githubusercontent.com/62099222/143728269-e3e6cacc-f5ac-4219-8268-7df9acb90c4d.PNG)
![捕获2](https://user-images.githubusercontent.com/62099222/143728314-eaf5637f-3adf-4de9-8e82-531eb8ae5c17.PNG)

**Comment by TakHemlata** [comment]
Hello,

I checked the code at my end and its working fine.
I suggest you to install soundfile the latest version or try with librosa.

Thanks

**Comment by mabangbangtadie** [comment]
Thank you, I will next try

**Comment by mabangbangtadie** [comment]
I have solve the question according reinstanlling soundfile,thank u，Use chinese language is  niu bi plus!!!
