### ISSUE TITLE
the Experimental enviroment

### ISSUE THREAD

**Issue by TingziGITHUB** [eurecom-asp/RawGAT-ST-antispoofing#6]
hello, thank you for your work. I want to reproduce this project, but i don't know the type of GPU and the time to train the model. Thank you for your help.

**Comment by Usgupta** [comment]
i also would like to know this!

**Comment by GeWanying** [comment]
Hi @TingziGITHUB @Usgupta, the author of this work @TakHemlata has graduated and left our group. Sorry for the late reply from our side.

All experiments are done on one GeForce RTX 3090 GPU, and training takes estimated 8 to 10 hours to finish.
